version: 2
jobs:            
  build_static_test:
    working_directory: /root/FISCO-BCOS
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update 
            apt-get install -y git g++ make curl lcov build-essential cmake libssl-dev libleveldb-dev libsnappy-dev
      - checkout
      - restore_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Compile
          command: |
            mkdir -p build && cd build 
            cmake -DSTATIC_BUILD=ON -DTESTS=ON -DCOVERAGE=ON .. 
            make -j2
      - run:
          name: Unit test
          command: |
            cd build
            CTEST_OUTPUT_ON_FAILURE=TRUE make test
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - deps
      - run:
          name: Upload Coverage
          command: |
            rm -rf deps
            bash <(curl -s https://codecov.io/bash) -C $CIRCLE_SHA1 -g ./deps/**

  build_test_guomi:
    working_directory: /root/FISCO-BCOS-gm
    docker:
        - image: centos:7
    steps:
      - run:
          name: Install dependencies
          command: |
            yum install -y epel-release
            yum install -y git make gcc-c++ cmake3 openssl-devel leveldb-devel
      - checkout
      - restore_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Compile
          command: |
            mkdir -p build && cd build
            cmake3 -DBUILD_GM=ON -DTESTS=ON -DEASYLOG=ON ..
            make -j2
      - run:
          name: Unit test
          command: |
            cd build
            ./bin/test-fisco-bcos -- --testpath=../test/data/ 
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - deps

  deploy_static:
    working_directory: /root/FISCO-BCOS
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update 
            apt-get install -y git clang make curl build-essential cmake libssl-dev libleveldb-dev libsnappy-dev
      - checkout
      - restore_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Compile
          command: |
            mkdir -p build && cd build 
            CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -DSTATIC_BUILD=ON .. 
            make -j2
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - deps
      - run:
          name: Upload binary
          command: |
            cd build/bin
            strip fisco-bcos
            tar -zcf fisco-static.tar.gz fisco-bcos
      - store_artifacts:
          path: /root/FISCO-BCOS/build/bin/fisco-static.tar.gz
          destination: fisco-static.tar.gz

  deploy_guomi:
    working_directory: /root/FISCO-BCOS
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update 
            apt-get install -y git clang make curl build-essential cmake libssl-dev libleveldb-dev libsnappy-dev
      - checkout
      - restore_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Compile
          command: |
            mkdir -p build && cd build 
            CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -DSTATIC_BUILD=ON -DBUILD_GM=ON .. 
            make -j2
      - save_cache:
          key: dependency-cache-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - deps
      - run:
          name: Upload binary
          command: |
            cd build/bin
            strip fisco-bcos
            tar -zcf fisco-static-gm.tar.gz fisco-bcos
      - store_artifacts:
          path: /root/FISCO-BCOS/build/bin/fisco-static-gm.tar.gz
          destination: fisco-static-gm.tar.gz

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_static_test
      - build_test_guomi
  deploy:
    jobs:
      - deploy_static:
          filters:
            branches:
              only: 
                - /release-2.*/
            tags:
              only: 
                - /v2.*/
      - deploy_guomi:
          filters:
            branches:
              only: 
                - /release-2.*/
            tags:
              only: 
                - /v2.*/
